### ISSUE TITLE
The connection to ws://127.0.0.1:8007/ was interrupted while the page was loading.

### ISSUE THREAD

**Issue by surajdevesan** [charlieroberts/sharejs.codemirror.example#1]
plss help ,this is the error i am receiving.. I cant integrate codemirro with sharejs 
The connection to ws://127.0.0.1:8007/ was interrupted while the page was loading.

**Comment by charlieroberts** [comment]
You might need to be careful about which versions of the modules (in particular codemirror and share) you install. Did you install via `npm install`?

**Comment by charlieroberts** [comment]
Closing due to lack of response.
